elasticsearch.clusterindex.*:
  type: config_entity
  label: 'Elasticsearch Cluster Indices'
  mapping:
    index_name:
      type: string
      label: 'Index Name'
    num_of_shards:
      type: string
      label: 'Shards'
    num_of_replica:
      type: string
      label: 'Replica'
